# https://taskfile.dev
version: '3'
vars:
  BINFILE: calcdate

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task -a

  tests:
    desc: "Run tests"
    dir: e2etests
    cmds:
      - venom run testsuite.yml --output-dir log

  snapshot:
    desc: "Create a snapshot"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    desc: "Create a release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean

  godoc:
    desc: "Run godoc server"
    cmds:
      - godoc -http=:6060
    