# https://taskfile.dev
version: '3'
vars:
  BINFILE: calcdate

tasks:
  default:
    cmds:
      - CGO_ENABLED=0 go build .
      - upx -q {{.BINFILE}}
    # silent: true
    method: checksum
    generates:
      - "{{.BINFILE}}"

  tests:
    dir: e2etests
    cmds:
      - venom run testsuite.yml --output-dir log

  snapshot:
    cmds:
      - GITLAB_TOKEN="" goreleaser --rm-dist --snapshot
    
  release:
    cmds:
      - GITLAB_TOKEN="" goreleaser --rm-dist

  godoc:
    cmds:
      - godoc -http=:6060
    